### ISSUE TITLE
Some alignment in the various information windows would be nice

### ISSUE THREAD

**Issue by jariarkko** [jariarkko/psgeo#130]
We jump on new web pages (new tab, e.g., upon clicking on an article), we create Google Maps info popups (e.g., cave basic information popup, or the other map tools popup), and we create entirely new windows (cave classification).

Not entirely clear to me what the choices are here, and if we're making the right choices. I think the cave basic information popup needs to be on this page, because changing all the time to a different page would be distracting. And articles and cave classifications are long/large enough that they deserve their own page. But what's the logic in new windows vs. jumping to a new address in a new tab? Or could we put more things Google Maps info popups?

**Comment by ralfstrandell** [comment]
- **cave information** should go into an _infowindow_. That's the intended use of an Infowindow, really.

- **articles and cave maps** opened from the infowindow should open _in a new tab_ (not the current one) because they are long reads and also take the reader away. This is the UX designers view [name in pm].

- The **cave classification window** is a reference sheet that should remain visible at the same time as the map itself (do not replace current page, do not open in a tab) and it must be movable so that it does not cover any caves. All this means that it must be _a popup window_. Think of it as, if not a tool palette, then at least as a reference book, or contextual help. I for example, want to drag it to the second screen while I browse the map. Then I can easily reference it whenever I open a cave infowindow as see something cryptic like "B,BEF" or "HD3". Please note that this popup window could also show climbing grades, ski piste grades, and other classifications depending on sport on the map.

That was the easy stuff.

- The **filter window** could open up as a tool palette, but I believe that we can live with an Infowindow, too. Having too many popups can be annoying, and especially if the one you need to USE gets buried under other windows. So perhaps it is best to just keep it on the map as it is now. The fact that the infowindow is tied to coordinates and has a sharp tip looks a bit strange, but is bearable.

- Same is true for the **About window** and **More maps**...

**Comment by jariarkko** [comment]
Good analysis!

(There may be a subgroup of people -- and I'm in that group -- that usually has full screen browser windows, and for them the new window doesn't work so well. But I understand the logic now. Thanks!)

**Comment by ralfstrandell** [comment]
Instead of a pop-up, the _reference window_ could also be hidden as a side panel and slide open when one clicks on a button (typically a triangular icon that point to the right or down). It would remain visible as long as the user wants, and on single-screen full-screen and on mobile, and everywhere, and the map would remain movable. Of course then, it cannot be dragged onto another screen (unless it has a pin icon and it can be unpinned and ... well lots of work).

Of course, again, a side panel that slides open once one clicks on a triangle icon in some corner...
