### ISSUE TITLE
i18n: combine caveletsText(), mediumCavesText() and bigCavesText(); use {{paceholderN}} for values in accordance with Localization Best Practices (a follow-up of #139)

### ISSUE THREAD

**Issue by ralfstrandell** [jariarkko/psgeo#140]
https://developer.mozilla.org/en-US/docs/Mozilla/Localization/Localization_content_best_practices

**Comment by jariarkko** [comment]
I'm not sure I fully understand this issue. Using a getText type approach is good (as long as code refers to IDs and not the english strings). Using placeholders for values like numbers, URLs, names, etc. is also really good. That you can replace $Var with Var's value is therefore good. Is this what this issue is about?

(But if the issue is about combining the three cave texts, I'm not sure what we're doing. Clearly we need the capability to have the three different strings in the user interface. Also, the current code is capable of adjusting text length depending on screen size. Both of those capabilities should be retained even if we change the code internally to a nicer internal translation API.

Or is this issue about a different replacement style? Currently, you pass the argument for the numbers in the function. This is very easy for the caller and imho according to the design guidelines. You can change it of course to just returning $VAR1...$VAR2 and then replacing afterwards. But if we do that, it would be helpful to create a second function that would do the replacement, and again take the numbers as arguments. This would reduce the code size in the calling function, and those filter creating code pieces are already complex enough, so I don't think we need

   text = getText(id);
   text = replace(text,"VAR1",n1);
   text = replace(text,"VAR2",n2);

when we could simply do

   text = getTextReplacements(id,{"VAR1":n1,"VAR2":,n2});

or

   text = getTextTwoVars(id,n1,n2);

or similar.)

**Comment by ralfstrandell** [comment]
The strings are kept separate and unchanged.
The generating functions can be combined.
The shorter versions must also be kept available.
Hence: no change in actual strings, no change in capabilities, just internal code cleanup.

We can take a look at how similar things (slightly differing versions of a translation) have been achieved in other software. Long/short text can surely be done in a standardized manner because tools such as Gettext or Jed also support various modifiers. I can look how they have solved these modifiers... and then implement something not wildly different.

**Comment by ralfstrandell** [comment]
It is best to pass the values in the function call, as you say.

It would be an array of values. An array of strings of course. Probably something like xgetText(stringId,Array). 

Something similar has been used GNU Gettext too: gettext, dgettext, ...

**Comment by jariarkko** [comment]
ok!

**Comment by ralfstrandell** [comment]
This: text = getTextTwoVars(id,n1,n2);
is good, let's just make it
    getTextManyVars(texId,[n1,n2,...,nN],needShort)
and the use
    for (X of array) -loop
and inside it increment a counter i and replace {{string i}} with ni
Then we can have zero, one, two, or twenty things to replace.
The needShort boolean can make the script fetch stringIdShort instead of stringId.

**Comment by jariarkko** [comment]
ok
