### ISSUE TITLE
Makefile needs an indent/tab checker to avoid the use of tabs in source code

### ISSUE THREAD

**Issue by jariarkko** [jariarkko/psgeo#164]
(Tabs often cause problems if editors use different settings and/or cannot be configured)

**Comment by ralfstrandell** [comment]
Now we are working in opposite directions.

_The good:_ I have been using the tab key because it makes indention easy and quick and is customizable. Pressing the space key 6, 12 or 18 (or 8, 16, 24) times is hard work (ok, I can press and hold, but...).

_The bad:_ Tabs tend to work well at the beginning of lines, but can cause problems when used within lines. Things can move 'out of sync' depending on the width of the tab.

I think I have never encountered an editor where tab width would not be configurable. Even in visual editor (vi) I can :set tabstop N. No, wait, maybe tabstop configuration is missing from ed and pico? I used those on VAX/VMS...

Possible solutions:

1) We need to have some policies or a style guide in place.
- Indention policy: How much indented? How if-then-else statements are indented, or loops, and many more.
- One-line if's when they are short? Or two lines? Or always three?
- When should we use && and || ?
- where do we want comments? Are end-of-line comments OK? Or only if they are 1-3 words?

2) I can set _:expandtabs_ in vi, so than when I press tab, a number of spaces is inserted. Best of two worlds.

3) I can replace all the tabs with spaces. It's simple
:set tabstop 3 (any number)
:expandtab (meas that tabs get replaced with spaces)
:retab (do!)
and done.

**Comment by ralfstrandell** [comment]
I can do these changes swiftly, when asked... I just need inforamation.

**Comment by jariarkko** [comment]
The software has been using indent of 4, so lets continue to use that. I recommend that you use your option 2 in vi. Let me know if that causes any difficulties. All files are now in space mode. All we need to do is to keep them in that.

(And when I say we shouldn't use TABs, i mean of course the charater TAB, obviously your editor will still allow you to press TAB but it should fill in the space with space characters.)

**Comment by jariarkko** [comment]
(And sorry, it was not my intent to work against each other. You should obviously have a well working setup for your editor, and if this change prohibits that then the change is broken and will need to be fixed :-) )

**Comment by jariarkko** [comment]
The makefile was changed to relax the rules. It will now only warn if TAB characters have been used, pending further discussion and thinking on this issue.
