### ISSUE TITLE
Psgeo should have a way to display its version somehow

### ISSUE THREAD

**Issue by jariarkko** [jariarkko/psgeo#175]

**Comment by ralfstrandell** [comment]
- Curated version numbering is one possibility, but what would you think of a "build date" -type versioning?
- Could we place version numbers etc in the page head as a meta tag (generator, application-name, title)?

**generator** The value must be a free-form string that identifies one of the software packages used to generate the document. This value must not be used on pages whose markup is not generated by software, e.g. pages whose markup was written by a user in a text editor.

**application-name** The value must be a short free-form string giving the name of the web application that the page represents. [...] User agents may use the application name in UI in preference to the page's title, since ...

**the title** might include status messages and the like relevant to the status of the page at a particular moment in time instead of just being the name of the application.

**Comment by jariarkko** [comment]
Thanks. Will look.

**Comment by jariarkko** [comment]
This is useful reading: https://stackoverflow.com/questions/37814286/how-to-manage-the-version-number-in-git

**Comment by jariarkko** [comment]
Works now. Psgeolib has a variable that contains the version number, and it is shown in the about window. The variable can be updated manually, but it can also be automatically updated with "make versionupdate". The version numbers should correspond to git tags, e.g, "v1.2.1" for the current version. The git tag -a "va.b.c" command can be used to tag the current version.
