### ISSUE TITLE
Would be nice to have a "hole" category for <2m caves

### ISSUE THREAD

**Issue by jariarkko** [jariarkko/psgeo#20]

**Comment by ralfstrandell** [comment]
Note though, that we have omitted hundreds of caves shorter that 10m from the caving associations database, and the list in Suomen luolat only contains cavities where three adults can comfortably take shelter. A more informative splitting of the range at 5, 25 and 50.

(For example: less than five, 5-24.9, 25-49.9, 50 or more. One could argue that 10, 25, 50 might be better because the list of sub-10m caves is severely lacking)

**Comment by jariarkko** [comment]
Maybe.

There's no reason to immediately do anything.

(But if we eventually do something, lets keep in mind that the database has many purposes. It would be good to have a default view that makes sense for most viewers. Part of the reason why I wanted to filter the really tiny caves out, even if I myself would click them to be visible when looking for something. Also, Jarmo wanted configurable ranges. Maybe that's too much complexity for the average user's needs, though.)

**Comment by ralfstrandell** [comment]
With the recent addition of user-changeable range limits, one can open the MoreFilter window and turn down the lower limit to 2m (or two of whatever unit) to achieve this.

The counting of approx length sites in each length etc category is affected, but it is a minor issue, that can be addressed in another ticket.

Considering this feature to be available now, and thus closing this ticket.
