### ISSUE TITLE
psgeodb.js: Only finnish (d.fi) and english (d.en) descriptions are processed

### ISSUE THREAD

**Issue by ralfstrandell** [jariarkko/psgeo#208]
A small change in the nested if-then-else is warranted: access d.language or, if it is undefined, d.en, or return undefined by default.

**Comment by jariarkko** [comment]
The tests now work, some code cleanup has been done, language support for finding categories has been improved, test inputs and results have been modified appropriately.

The root cause for the errors was that

- lack of test updates and analysis of what changes a code change had
- hasty fixes (by me) to the test inputs with a typo which led to merging/classification not working
- lack of recognising non-en/fi languages.

But as said, it all works now 👍

The new code goes through the languages supported by the language module. I chose that approach over going over any language given in the input. You could also have done the latter. But this is a special feature that we use to recognise text, and going more forward, I expect the inputs to use the classification in the "sa", so at *some* point we can remove this code.
