### ISSUE TITLE
Consider zooming the map as soon as position is found

### ISSUE THREAD

**Issue by jarmoruuth** [jariarkko/psgeo#402]
Consider zooming the map as soon as position is found. Now it takes quite a long time before map is zoomed to current location when location button is pressed.

**Comment by ralfstrandell** [comment]
It is 10 times faster now. Some browsers do _ignore_ geolocation settings and use a cached value at first. Because of this we ignore the first position. Earlier it was 10 first positions. One would not want a wrongfully centered map zoomed in, and the obvious remedy of constant recentering might not be that great after all. Give the user freedom of map placement while doing an initial centering with a true position.
